// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcuymqwqcoogcjngscav.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jdXltcXdxY29vZ2NqbmdzY2F2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MTY4NDgsImV4cCI6MjA2MDQ5Mjg0OH0.SSM_39fEeBEiBtBRlwquwDpwzn7nhhbRKuPpi4Fv3PU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);